name: PokedexSample
options: 
    deploymentTarget:
        iOS: 11.0
fileGroups:
targets:
  PokedexSample:
    type: application
    platform: iOS
    sources: [PokedexSample]
    settings:
      CURRENT_PROJECT_VERSION: 1
    dependencies:
    - target: API
    - target: Presentation
  API:
    type: framework
    platform: iOS
    sources: [API]
    dependencies:
      - carthage: Alamofire
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
