name: PokedexSample
options: 
    deploymentTarget:
        iOS: 11.0
fileGroups:
targets:
  PokedexSample:
    type: application
    platform: iOS
    sources: [PokedexSample]
    settings:
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedexSample
      CODE_SIGN_STYLE: Automatic
    dependencies:
    - target: Presentation
    - target: DataStore
    - target: Domain
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    setting:
        PRODUCT_BUNDLE_IDENTIFIER: pokedexSample.DataStore
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - carthage: Alamofire
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    setting:
        PRODUCT_BUNDLE_IDENTIFIER: pokedexSample.Presentation
        CODE_SIGN_STYLE: Automatic
    dependencies:
        - target: DataStore
        - target: Domain
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    setting:
        PRODUCT_BUNDLE_IDENTIFIER: pokedexSample.Domain
        CODE_SIGN_STYLE: Automatic
    dependencies:
        - target: DataStore
